-- Public part discussion; writes require the authenticated author.
begin;
create table if not exists public.part_comments (
 id bigint generated by default as identity primary key,
 part_id bigint not null references public.parts(id) on delete cascade,
 author_id uuid not null references public.profiles(id) on delete cascade,
 content text not null check (char_length(btrim(content)) between 1 and 1500),
 created_at timestamptz not null default now()
);
create index if not exists part_comments_part_created_idx on public.part_comments(part_id, created_at desc, id desc);
alter table public.part_comments enable row level security;
revoke all on public.part_comments from anon, authenticated;
grant select on public.part_comments to anon, authenticated;
grant insert, delete on public.part_comments to authenticated;
grant usage, select on sequence public.part_comments_id_seq to authenticated;
drop policy if exists part_comments_read on public.part_comments;
create policy part_comments_read on public.part_comments for select to anon, authenticated using (true);
drop policy if exists part_comments_insert on public.part_comments;
create policy part_comments_insert on public.part_comments for insert to authenticated with check (
 (select auth.uid()) = author_id and exists (select 1 from public.parts where id = part_id and is_active = true)
);
drop policy if exists part_comments_delete on public.part_comments;
create policy part_comments_delete on public.part_comments for delete to authenticated using ((select auth.uid()) = author_id);
commit;
notify pgrst, 'reload schema';
